name: Modify System Time and Create Folder

on:
  push:
    branches:
      - main

jobs:
  modify-system-time:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set timezone to Shanghai
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        echo "Timezone set to Shanghai"
        
    - name: Set current date
      id: set_date
      run: echo "::set-output name=current_date::$(date +'%Y-%m-%d')"

    - name: Use current date
      run: echo "Current Date is ${{ steps.set_date.outputs.current_date }}"
    - name: Create folder
      id: create_folder
      run: mkdir ${{ steps.set_date.outputs.current_date }}

    - name: Set folder path
      id: set_folder_path
      run: echo "::set-env name=FOLDER_PATH::${{ steps.create_folder.outputs.current_date }}"

    - name: Output folder path
      run: echo "Folder Path:$FOLDER_PATH"

        
